version: "3.5"
services:
  weatherapi-proxy:
    image: "noahnc/weatherapi-proxy:latest"
    hostname: weatherapi-proxy
    ports:
      - "6443:443"
    depends_on:
       - weatherapi-frontend
       - weatherapi-backend
    deploy:
      mode: global
  weatherapi-frontend:
    build: .
    image: "bursacmilan/nbs-weatherapi-frontend:latest"
    hostname: weatherapi-frontend
    deploy:
      replicas: 2
  weatherapi-backend:
    build: .
    image: "bursacmilan/nbs-weatherapi-backend:latest"
    hostname: weatherapi-backend
    deploy:
      replicas: 2
